name: Inject API Secrets

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  inject-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace API keys in code.js
        run: |
          sed -i "s|const apiKey = \".*\";|const apiKey = \"${{ secrets.GOOGLE_API_KEY }}\";|" code.js
          sed -i "s|const cx = \".*\";|const cx = \"${{ secrets.GOOGLE_CX }}\";|" code.js