name: Inject API Secrets into index.html

on:
  push:
    branches: [main]

jobs:
  inject-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Replace placeholders with secrets
      run: |
        sed -i "s/YOUR_API_KEY/${{ secrets.GOOGLE_API_KEY }}/g" index.html
        sed -i "s/YOUR_CX/${{ secrets.GOOGLE_CX }}/g" index.html

    - name: Commit and push updated index.html
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add index.html
        git commit -m "Inject API secrets into index.html"
        git push
